const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const SUCCESS = 200;
const NOT_FOUND = 404;
const CREATED = 201;
const SERVER_ERROR = 500;

module.exports = {
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  SUCCESS,
  NOT_FOUND,
  CREATED,
  SERVER_ERROR,
};
